FROM arangodb:3.11

# Disable authentication
ENV ARANGO_NO_AUTH=1

EXPOSE 8529

# ENTRYPOINT cannot be overridden by Railway start command
ENTRYPOINT ["arangod"]
CMD ["--server.endpoint", "tcp://0.0.0.0:8529"]
